### PR TITLE
Add Python v3.8 compatibility

### PR DESCRIPTION
**Pull request by sethaxen**
Currently `pyproject.toml` pins the supported Python version to 3.7 even though the classifiers indicate that Python 3.8 is supported. This PR adds v3.8 compatibility and updates the workflows to both test and build wheels for v3.8. Locally the tests pass on my machine.

### CODE REVIEW

**Comment by sethaxen** [comment]
Should there be a test workflow on CI?

cc @vincentadam87

**Comment by sethaxen** [comment]
Ah, it seems CI does run, just on my branch and not listed here. Here we see the tests pass: https://github.com/sethaxen/banded_matrices/actions/runs/4256153473

**Comment by vincentadam87** [comment]
With delay, the changes look good to me.

**Comment by vincentadam87** [comment]
Any idea why the tests fail on push?
https://github.com/secondmind-labs/banded_matrices/actions/runs/4305958752/jobs/7509130276
@sethaxen

**Pull request merged**
